import Testing
@testable import Domain

@Suite
struct WinBackOfferTests {

    @Test func `win-back offer carries subscriptionId and eligibility fields`() {
        let offer = WinBackOffer(
            id: "wb-1", subscriptionId: "sub-1",
            referenceName: "Lapsed", offerId: "lapsed25",
            duration: .oneMonth, offerMode: .freeTrial, periodCount: 1,
            customerEligibilityPaidSubscriptionDurationInMonths: 3,
            customerEligibilityTimeSinceLastSubscribedMin: 1,
            customerEligibilityTimeSinceLastSubscribedMax: 6,
            customerEligibilityWaitBetweenOffersInMonths: 2,
            startDate: "2026-04-01", endDate: "2026-12-31",
            priority: .high, promotionIntent: .useAutoGeneratedAssets
        )
        #expect(offer.subscriptionId == "sub-1")
        #expect(offer.customerEligibilityTimeSinceLastSubscribedMin == 1)
        #expect(offer.customerEligibilityTimeSinceLastSubscribedMax == 6)
        #expect(offer.priority == .high)
    }

    @Test func `affordances include listOffers, update, delete, listPrices`() {
        let offer = WinBackOffer(
            id: "wb-1", subscriptionId: "sub-1", referenceName: "X",
            offerId: "x", duration: .oneMonth, offerMode: .freeTrial, periodCount: 1,
            customerEligibilityPaidSubscriptionDurationInMonths: 1,
            customerEligibilityTimeSinceLastSubscribedMin: 1,
            customerEligibilityTimeSinceLastSubscribedMax: 6,
            startDate: "2026-04-01", priority: .normal
        )
        #expect(offer.affordances["listOffers"] == "asc win-back-offers list --subscription-id sub-1")
        #expect(offer.affordances["update"] == "asc win-back-offers update --offer-id wb-1")
        #expect(offer.affordances["delete"] == "asc win-back-offers delete --offer-id wb-1")
        #expect(offer.affordances["listPrices"] == "asc win-back-offers prices list --offer-id wb-1")
    }

    @Test func `price affordances include listPrices`() {
        let price = WinBackOfferPrice(id: "p-1", offerId: "wb-1", territory: "USA", subscriptionPricePointId: "spp-1")
        #expect(price.affordances["listPrices"] == "asc win-back-offers prices list --offer-id wb-1")
    }
}
