import Foundation
import Testing
@testable import Domain

@Suite
struct WinBackOfferCodableTests {

    @Test func `roundtrip preserves all required fields`() throws {
        let offer = WinBackOffer(
            id: "wb-1", subscriptionId: "sub-1",
            referenceName: "Lapsed", offerId: "lapsed25",
            duration: .oneMonth, offerMode: .freeTrial, periodCount: 1,
            customerEligibilityPaidSubscriptionDurationInMonths: 3,
            customerEligibilityTimeSinceLastSubscribedMin: 1,
            customerEligibilityTimeSinceLastSubscribedMax: 6,
            customerEligibilityWaitBetweenOffersInMonths: 2,
            startDate: "2026-04-01", endDate: "2026-12-31",
            priority: .high, promotionIntent: .useAutoGeneratedAssets
        )
        let data = try JSONEncoder().encode(offer)
        let decoded = try JSONDecoder().decode(WinBackOffer.self, from: data)
        #expect(decoded == offer)
    }

    @Test func `roundtrip omits optional fields when nil`() throws {
        let offer = WinBackOffer(
            id: "wb-1", subscriptionId: "sub-1",
            referenceName: "X", offerId: "x",
            duration: .oneMonth, offerMode: .freeTrial, periodCount: 1,
            customerEligibilityPaidSubscriptionDurationInMonths: 1,
            customerEligibilityTimeSinceLastSubscribedMin: 0,
            customerEligibilityTimeSinceLastSubscribedMax: 6,
            startDate: "2026-04-01",
            priority: .normal
        )
        let json = String(decoding: try JSONEncoder().encode(offer), as: UTF8.self)
        #expect(!json.contains("endDate"))
        #expect(!json.contains("promotionIntent"))
        #expect(!json.contains("customerEligibilityWaitBetweenOffersInMonths"))
    }

    @Test func `price roundtrip preserves territory and pricePointId`() throws {
        let price = WinBackOfferPrice(id: "p-1", offerId: "wb-1", territory: "USA", subscriptionPricePointId: "spp-1")
        let data = try JSONEncoder().encode(price)
        let decoded = try JSONDecoder().decode(WinBackOfferPrice.self, from: data)
        #expect(decoded == price)
    }
}
