@preconcurrency import AppStoreConnect_Swift_SDK
import Testing
@testable import Infrastructure
@testable import Domain

@Suite
struct SDKWinBackOfferRepositoryTests {

    @Test func `listWinBackOffers injects subscriptionId into each offer`() async throws {
        let stub = StubAPIClient()
        stub.willReturn(WinBackOffersResponse(
            data: [
                AppStoreConnect_Swift_SDK.WinBackOffer(
                    type: .winBackOffers, id: "wb-1",
                    attributes: .init(
                        referenceName: "Lapsed", offerID: "lapsed25",
                        duration: .oneMonth, offerMode: .freeTrial, periodCount: 1,
                        customerEligibilityPaidSubscriptionDurationInMonths: 3,
                        customerEligibilityTimeSinceLastSubscribedInMonths: .init(minimum: 1, maximum: 6),
                        startDate: "2026-04-01",
                        priority: .high
                    )
                ),
            ],
            links: .init(this: "")
        ))

        let repo = SDKWinBackOfferRepository(client: stub)
        let result = try await repo.listWinBackOffers(subscriptionId: "sub-77")

        #expect(result.count == 1)
        #expect(result[0].subscriptionId == "sub-77")
        #expect(result[0].referenceName == "Lapsed")
        #expect(result[0].offerId == "lapsed25")
    }

    @Test func `listWinBackOffers maps eligibility range, priority and promotionIntent`() async throws {
        let stub = StubAPIClient()
        stub.willReturn(WinBackOffersResponse(
            data: [
                AppStoreConnect_Swift_SDK.WinBackOffer(
                    type: .winBackOffers, id: "wb-1",
                    attributes: .init(
                        referenceName: "X", offerID: "x",
                        duration: .oneMonth, offerMode: .freeTrial, periodCount: 1,
                        customerEligibilityPaidSubscriptionDurationInMonths: 3,
                        customerEligibilityTimeSinceLastSubscribedInMonths: .init(minimum: 2, maximum: 8),
                        customerEligibilityWaitBetweenOffersInMonths: 4,
                        startDate: "2026-04-01", endDate: "2026-12-31",
                        priority: .normal,
                        promotionIntent: .useAutoGeneratedAssets
                    )
                ),
            ],
            links: .init(this: "")
        ))

        let repo = SDKWinBackOfferRepository(client: stub)
        let result = try await repo.listWinBackOffers(subscriptionId: "sub-1")

        #expect(result[0].customerEligibilityTimeSinceLastSubscribedMin == 2)
        #expect(result[0].customerEligibilityTimeSinceLastSubscribedMax == 8)
        #expect(result[0].customerEligibilityWaitBetweenOffersInMonths == 4)
        #expect(result[0].endDate == "2026-12-31")
        #expect(result[0].priority == .normal)
        #expect(result[0].promotionIntent == .useAutoGeneratedAssets)
    }

    @Test func `updateWinBackOffer returns updated record with empty subscriptionId`() async throws {
        let stub = StubAPIClient()
        stub.willReturn(WinBackOfferResponse(
            data: AppStoreConnect_Swift_SDK.WinBackOffer(
                type: .winBackOffers, id: "wb-1",
                attributes: .init(
                    referenceName: "X", offerID: "x",
                    duration: .oneMonth, offerMode: .freeTrial, periodCount: 1,
                    customerEligibilityPaidSubscriptionDurationInMonths: 3,
                    customerEligibilityTimeSinceLastSubscribedInMonths: .init(minimum: 1, maximum: 6),
                    startDate: "2026-04-01",
                    priority: .high
                )
            ),
            links: .init(this: "")
        ))

        let repo = SDKWinBackOfferRepository(client: stub)
        let result = try await repo.updateWinBackOffer(
            offerId: "wb-1",
            startDate: nil, endDate: nil,
            priority: .high, promotionIntent: nil,
            paidSubscriptionDurationInMonths: nil,
            timeSinceLastSubscribedMin: nil, timeSinceLastSubscribedMax: nil,
            waitBetweenOffersInMonths: nil
        )

        #expect(result.id == "wb-1")
        #expect(result.priority == .high)
        #expect(result.subscriptionId == "")
    }

    @Test func `deleteWinBackOffer performs void request`() async throws {
        let stub = StubAPIClient()
        let repo = SDKWinBackOfferRepository(client: stub)
        try await repo.deleteWinBackOffer(offerId: "wb-1")
        #expect(stub.voidRequestCalled == true)
    }

    @Test func `listPrices injects offerId and maps territory + pricePoint`() async throws {
        let stub = StubAPIClient()
        stub.willReturn(WinBackOfferPricesResponse(
            data: [
                AppStoreConnect_Swift_SDK.WinBackOfferPrice(
                    type: .winBackOfferPrices, id: "p-1",
                    relationships: .init(
                        territory: .init(data: .init(type: .territories, id: "USA")),
                        subscriptionPricePoint: .init(data: .init(type: .subscriptionPricePoints, id: "spp-9"))
                    )
                ),
            ],
            links: .init(this: "")
        ))

        let repo = SDKWinBackOfferRepository(client: stub)
        let result = try await repo.listPrices(offerId: "wb-77")

        #expect(result[0].offerId == "wb-77")
        #expect(result[0].territory == "USA")
        #expect(result[0].subscriptionPricePointId == "spp-9")
    }
}
