import Mockable
import Testing
@testable import ASCCommand
@testable import Domain

private func makeOffer(id: String = "wb-1", subscriptionId: String = "sub-1") -> WinBackOffer {
    WinBackOffer(
        id: id, subscriptionId: subscriptionId, referenceName: "Lapsed",
        offerId: "lapsed25", duration: .oneMonth, offerMode: .freeTrial, periodCount: 1,
        customerEligibilityPaidSubscriptionDurationInMonths: 3,
        customerEligibilityTimeSinceLastSubscribedMin: 1,
        customerEligibilityTimeSinceLastSubscribedMax: 6,
        startDate: "2026-04-01", priority: .normal
    )
}

@Suite
struct WinBackOffersListTests {

    @Test func `lists win-back offers with affordances`() async throws {
        let mockRepo = MockWinBackOfferRepository()
        given(mockRepo).listWinBackOffers(subscriptionId: .any).willReturn([makeOffer()])

        let cmd = try WinBackOffersList.parse(["--subscription-id", "sub-1", "--pretty"])
        let output = try await cmd.execute(repo: mockRepo)

        #expect(output.contains("\"id\" : \"wb-1\""))
        #expect(output.contains("\"subscriptionId\" : \"sub-1\""))
    }
}

@Suite
struct WinBackOffersCreateTests {

    @Test func `create passes through eligibility, dates and prices`() async throws {
        let mockRepo = MockWinBackOfferRepository()
        given(mockRepo).createWinBackOffer(
            subscriptionId: .any, referenceName: .any, offerId: .any,
            duration: .any, offerMode: .any, periodCount: .any,
            paidSubscriptionDurationInMonths: .any,
            timeSinceLastSubscribedMin: .any,
            timeSinceLastSubscribedMax: .any,
            waitBetweenOffersInMonths: .any,
            startDate: .any, endDate: .any,
            priority: .any, promotionIntent: .any, prices: .any
        ).willReturn(makeOffer())

        let cmd = try WinBackOffersCreate.parse([
            "--subscription-id", "sub-1",
            "--reference-name", "Lapsed",
            "--offer-id", "lapsed25",
            "--duration", "ONE_MONTH",
            "--mode", "FREE_TRIAL",
            "--periods", "1",
            "--paid-months", "3",
            "--since-min", "1",
            "--since-max", "6",
            "--wait-months", "2",
            "--start-date", "2026-04-01",
            "--end-date", "2026-12-31",
            "--priority", "HIGH",
            "--promotion-intent", "USE_AUTO_GENERATED_ASSETS",
            "--price", "USA=spp-1",
        ])
        _ = try await cmd.execute(repo: mockRepo)

        verify(mockRepo).createWinBackOffer(
            subscriptionId: .value("sub-1"),
            referenceName: .value("Lapsed"),
            offerId: .value("lapsed25"),
            duration: .value(.oneMonth),
            offerMode: .value(.freeTrial),
            periodCount: .value(1),
            paidSubscriptionDurationInMonths: .value(3),
            timeSinceLastSubscribedMin: .value(1),
            timeSinceLastSubscribedMax: .value(6),
            waitBetweenOffersInMonths: .value(2),
            startDate: .value("2026-04-01"),
            endDate: .value("2026-12-31"),
            priority: .value(.high),
            promotionIntent: .value(.useAutoGeneratedAssets),
            prices: .matching { $0 == [WinBackOfferPriceInput(territory: "USA", pricePointId: "spp-1")] }
        ).called(1)
    }

    @Test func `throws when priority invalid`() async throws {
        let mockRepo = MockWinBackOfferRepository()
        let cmd = try WinBackOffersCreate.parse([
            "--subscription-id", "sub-1",
            "--reference-name", "X",
            "--offer-id", "x",
            "--duration", "ONE_MONTH",
            "--mode", "FREE_TRIAL",
            "--periods", "1",
            "--paid-months", "3",
            "--since-min", "1",
            "--since-max", "6",
            "--start-date", "2026-04-01",
            "--priority", "URGENT",
        ])
        await #expect(throws: (any Error).self) {
            try await cmd.execute(repo: mockRepo)
        }
    }
}

@Suite
struct WinBackOffersUpdateTests {

    @Test func `update passes through optional fields`() async throws {
        let mockRepo = MockWinBackOfferRepository()
        given(mockRepo).updateWinBackOffer(
            offerId: .any, startDate: .any, endDate: .any,
            priority: .any, promotionIntent: .any,
            paidSubscriptionDurationInMonths: .any,
            timeSinceLastSubscribedMin: .any,
            timeSinceLastSubscribedMax: .any,
            waitBetweenOffersInMonths: .any
        ).willReturn(makeOffer())

        let cmd = try WinBackOffersUpdate.parse([
            "--offer-id", "wb-1",
            "--priority", "HIGH",
            "--end-date", "2027-01-01",
        ])
        _ = try await cmd.execute(repo: mockRepo)

        verify(mockRepo).updateWinBackOffer(
            offerId: .value("wb-1"),
            startDate: .value(nil),
            endDate: .value("2027-01-01"),
            priority: .value(.high),
            promotionIntent: .value(nil),
            paidSubscriptionDurationInMonths: .value(nil),
            timeSinceLastSubscribedMin: .value(nil),
            timeSinceLastSubscribedMax: .value(nil),
            waitBetweenOffersInMonths: .value(nil)
        ).called(1)
    }
}

@Suite
struct WinBackOffersDeleteTests {

    @Test func `delete calls repo with offer id`() async throws {
        let mockRepo = MockWinBackOfferRepository()
        given(mockRepo).deleteWinBackOffer(offerId: .any).willReturn(())

        let cmd = try WinBackOffersDelete.parse(["--offer-id", "wb-1"])
        try await cmd.execute(repo: mockRepo)

        verify(mockRepo).deleteWinBackOffer(offerId: .value("wb-1")).called(1)
    }
}

@Suite
struct WinBackOffersPricesListTests {

    @Test func `lists prices with affordances`() async throws {
        let mockRepo = MockWinBackOfferRepository()
        given(mockRepo).listPrices(offerId: .any).willReturn([
            WinBackOfferPrice(id: "p-1", offerId: "wb-1", territory: "USA", subscriptionPricePointId: "spp-1")
        ])

        let cmd = try WinBackOffersPricesList.parse(["--offer-id", "wb-1", "--pretty"])
        let output = try await cmd.execute(repo: mockRepo)

        #expect(output.contains("\"id\" : \"p-1\""))
        #expect(output.contains("\"offerId\" : \"wb-1\""))
        #expect(output.contains("\"territory\" : \"USA\""))
    }
}
