public struct WinBackOffer: Sendable, Equatable, Identifiable {
    public let id: String
    /// Parent subscription identifier — injected by Infrastructure
    public let subscriptionId: String
    public let referenceName: String
    public let offerId: String
    public let duration: SubscriptionOfferDuration
    public let offerMode: SubscriptionOfferMode
    public let periodCount: Int
    public let customerEligibilityPaidSubscriptionDurationInMonths: Int
    public let customerEligibilityTimeSinceLastSubscribedMin: Int
    public let customerEligibilityTimeSinceLastSubscribedMax: Int
    public let customerEligibilityWaitBetweenOffersInMonths: Int?
    public let startDate: String
    public let endDate: String?
    public let priority: WinBackOfferPriority
    public let promotionIntent: WinBackOfferPromotionIntent?

    public init(
        id: String,
        subscriptionId: String,
        referenceName: String,
        offerId: String,
        duration: SubscriptionOfferDuration,
        offerMode: SubscriptionOfferMode,
        periodCount: Int,
        customerEligibilityPaidSubscriptionDurationInMonths: Int,
        customerEligibilityTimeSinceLastSubscribedMin: Int,
        customerEligibilityTimeSinceLastSubscribedMax: Int,
        customerEligibilityWaitBetweenOffersInMonths: Int? = nil,
        startDate: String,
        endDate: String? = nil,
        priority: WinBackOfferPriority,
        promotionIntent: WinBackOfferPromotionIntent? = nil
    ) {
        self.id = id
        self.subscriptionId = subscriptionId
        self.referenceName = referenceName
        self.offerId = offerId
        self.duration = duration
        self.offerMode = offerMode
        self.periodCount = periodCount
        self.customerEligibilityPaidSubscriptionDurationInMonths = customerEligibilityPaidSubscriptionDurationInMonths
        self.customerEligibilityTimeSinceLastSubscribedMin = customerEligibilityTimeSinceLastSubscribedMin
        self.customerEligibilityTimeSinceLastSubscribedMax = customerEligibilityTimeSinceLastSubscribedMax
        self.customerEligibilityWaitBetweenOffersInMonths = customerEligibilityWaitBetweenOffersInMonths
        self.startDate = startDate
        self.endDate = endDate
        self.priority = priority
        self.promotionIntent = promotionIntent
    }
}

public enum WinBackOfferPriority: String, Sendable, Codable, Equatable {
    case high = "HIGH"
    case normal = "NORMAL"
}

public enum WinBackOfferPromotionIntent: String, Sendable, Codable, Equatable {
    case notPromoted = "NOT_PROMOTED"
    case useAutoGeneratedAssets = "USE_AUTO_GENERATED_ASSETS"
}

extension WinBackOffer: Codable {
    enum CodingKeys: String, CodingKey {
        case id, subscriptionId, referenceName, offerId, duration, offerMode, periodCount
        case customerEligibilityPaidSubscriptionDurationInMonths
        case customerEligibilityTimeSinceLastSubscribedMin
        case customerEligibilityTimeSinceLastSubscribedMax
        case customerEligibilityWaitBetweenOffersInMonths
        case startDate, endDate, priority, promotionIntent
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        subscriptionId = try c.decode(String.self, forKey: .subscriptionId)
        referenceName = try c.decode(String.self, forKey: .referenceName)
        offerId = try c.decode(String.self, forKey: .offerId)
        duration = try c.decode(SubscriptionOfferDuration.self, forKey: .duration)
        offerMode = try c.decode(SubscriptionOfferMode.self, forKey: .offerMode)
        periodCount = try c.decode(Int.self, forKey: .periodCount)
        customerEligibilityPaidSubscriptionDurationInMonths =
            try c.decode(Int.self, forKey: .customerEligibilityPaidSubscriptionDurationInMonths)
        customerEligibilityTimeSinceLastSubscribedMin =
            try c.decode(Int.self, forKey: .customerEligibilityTimeSinceLastSubscribedMin)
        customerEligibilityTimeSinceLastSubscribedMax =
            try c.decode(Int.self, forKey: .customerEligibilityTimeSinceLastSubscribedMax)
        customerEligibilityWaitBetweenOffersInMonths =
            try c.decodeIfPresent(Int.self, forKey: .customerEligibilityWaitBetweenOffersInMonths)
        startDate = try c.decode(String.self, forKey: .startDate)
        endDate = try c.decodeIfPresent(String.self, forKey: .endDate)
        priority = try c.decode(WinBackOfferPriority.self, forKey: .priority)
        promotionIntent = try c.decodeIfPresent(WinBackOfferPromotionIntent.self, forKey: .promotionIntent)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(id, forKey: .id)
        try c.encode(subscriptionId, forKey: .subscriptionId)
        try c.encode(referenceName, forKey: .referenceName)
        try c.encode(offerId, forKey: .offerId)
        try c.encode(duration, forKey: .duration)
        try c.encode(offerMode, forKey: .offerMode)
        try c.encode(periodCount, forKey: .periodCount)
        try c.encode(customerEligibilityPaidSubscriptionDurationInMonths,
                     forKey: .customerEligibilityPaidSubscriptionDurationInMonths)
        try c.encode(customerEligibilityTimeSinceLastSubscribedMin,
                     forKey: .customerEligibilityTimeSinceLastSubscribedMin)
        try c.encode(customerEligibilityTimeSinceLastSubscribedMax,
                     forKey: .customerEligibilityTimeSinceLastSubscribedMax)
        try c.encodeIfPresent(customerEligibilityWaitBetweenOffersInMonths,
                              forKey: .customerEligibilityWaitBetweenOffersInMonths)
        try c.encode(startDate, forKey: .startDate)
        try c.encodeIfPresent(endDate, forKey: .endDate)
        try c.encode(priority, forKey: .priority)
        try c.encodeIfPresent(promotionIntent, forKey: .promotionIntent)
    }
}

extension WinBackOffer: Presentable {
    public static var tableHeaders: [String] {
        ["ID", "Reference Name", "Offer ID", "Duration", "Mode", "Periods", "Priority"]
    }
    public var tableRow: [String] {
        [id, referenceName, offerId, duration.rawValue, offerMode.rawValue, String(periodCount), priority.rawValue]
    }
}

extension WinBackOffer: AffordanceProviding {
    public var structuredAffordances: [Affordance] {
        _ = RESTPathResolver._winBackOfferRoutes
        return [
            Affordance(key: "delete", command: "win-back-offers", action: "delete", params: ["offer-id": id]),
            Affordance(key: "listOffers", command: "win-back-offers", action: "list", params: ["subscription-id": subscriptionId]),
            Affordance(key: "listPrices", command: "win-back-offers prices", action: "list", params: ["offer-id": id]),
            Affordance(key: "update", command: "win-back-offers", action: "update", params: ["offer-id": id]),
        ]
    }
}

extension RESTPathResolver {
    static let _winBackOfferRoutes: Void = {
        registerRoute(
            command: "win-back-offers",
            parentParam: "subscription-id",
            parentSegment: "subscriptions",
            segment: "win-back-offers"
        )
        registerRoute(
            command: "win-back-offers prices",
            parentParam: "offer-id",
            parentSegment: "win-back-offers",
            segment: "prices"
        )
    }()
}

public struct WinBackOfferPrice: Sendable, Equatable, Identifiable {
    public let id: String
    public let offerId: String
    public let territory: String?
    public let subscriptionPricePointId: String?

    public init(id: String, offerId: String, territory: String? = nil, subscriptionPricePointId: String? = nil) {
        self.id = id
        self.offerId = offerId
        self.territory = territory
        self.subscriptionPricePointId = subscriptionPricePointId
    }
}

extension WinBackOfferPrice: Codable {
    enum CodingKeys: String, CodingKey {
        case id, offerId, territory, subscriptionPricePointId
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        offerId = try c.decode(String.self, forKey: .offerId)
        territory = try c.decodeIfPresent(String.self, forKey: .territory)
        subscriptionPricePointId = try c.decodeIfPresent(String.self, forKey: .subscriptionPricePointId)
    }

    public func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(id, forKey: .id)
        try c.encode(offerId, forKey: .offerId)
        try c.encodeIfPresent(territory, forKey: .territory)
        try c.encodeIfPresent(subscriptionPricePointId, forKey: .subscriptionPricePointId)
    }
}

extension WinBackOfferPrice: Presentable {
    public static var tableHeaders: [String] { ["ID", "Territory", "Price Point ID"] }
    public var tableRow: [String] { [id, territory ?? "", subscriptionPricePointId ?? ""] }
}

extension WinBackOfferPrice: AffordanceProviding {
    public var structuredAffordances: [Affordance] {
        _ = RESTPathResolver._winBackOfferRoutes
        return [
            Affordance(key: "listPrices", command: "win-back-offers prices", action: "list", params: ["offer-id": offerId]),
        ]
    }
}

public struct WinBackOfferPriceInput: Sendable, Equatable {
    public let territory: String
    public let pricePointId: String

    public init(territory: String, pricePointId: String) {
        self.territory = territory
        self.pricePointId = pricePointId
    }
}
